version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/sasimpson/goparent
    steps:
      - checkout
      - run: wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.70.zip
      - run: unzip -q go_appengine_sdk_linux_amd64-1.9.70.zip -d /home/circleci
      - run: echo 'export PATH=$PATH:/home/circleci/go_appengine' >> $BASH_ENV
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      # - run: go test -v github.com/sasimpson/goparent/datastore -run ^TestDatastoreSleepStatus 
      # todo later... this doesn't work.
      # - run: go test -coverprofile=/tmp/cover.out /go/src/github.com/sasimpson/goparent/...
      # - run: go tool cover -html=/tmp/cover.out -o /tmp/cover.html
      # - store_artifacts:
      #     path: /tmp/cover.out
      # - store_artifacts:
      #     path: /tmp/cover.html
        
workflows:
  version: 2
  test: 
    jobs: 
     - test