version: "3"

services:
  rethinkdb:
    container_name: goparent_rethinkdb
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ../rethinkdb_data:/data/rethinkdb_data

  service:
    container_name: goparent_service
    depends_on:
      - "rethinkdb"
    build: 
      dockerfile: docker/Dockerfile
      context: ../
    ports:
      - 8000:8000